// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBt6ubMWaqlWrTTcYq2J8SJCxaUxgX3gSs',
    appId: '1:154093082399:web:1b1c3f00e4df239d86422a',
    messagingSenderId: '154093082399',
    projectId: 'firstproject-b692b',
    authDomain: 'firstproject-b692b.firebaseapp.com',
    storageBucket: 'firstproject-b692b.firebasestorage.app',
    measurementId: 'G-36SR2V5JK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC15t5wFGQd0nKazxPaAsNxSrceAqHTzFk',
    appId: '1:154093082399:android:aec5fb6eb0b02d0686422a',
    messagingSenderId: '154093082399',
    projectId: 'firstproject-b692b',
    storageBucket: 'firstproject-b692b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_cJL20FJf7CXK6jUxt6P4DqCVnM8njkU',
    appId: '1:154093082399:ios:746fb69c9e9c2a5786422a',
    messagingSenderId: '154093082399',
    projectId: 'firstproject-b692b',
    storageBucket: 'firstproject-b692b.firebasestorage.app',
    iosBundleId: 'com.example.firebaseCrud',
  );
}
